apiVersion: v1
kind: Secret
metadata:
  name: {{ include "organigramma.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "organigramma.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.security.secretKey | b64enc | quote }}