# ConfigMap for Organigramma Web App configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: organigramma-config
  namespace: organigramma
  labels:
    app: organigramma-web-app
data:
  # Application settings
  APP_TITLE: "Organigramma Web App"
  APP_DESCRIPTION: "Sistema di gestione organigramma aziendale con storicizzazione"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  TIMEZONE: "Europe/Rome"
  
  # Server configuration
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8000"
  DEBUG: "false"
  RELOAD: "false"
  WORKERS: "4"
  ACCESS_LOG: "true"
  
  # Database configuration
  DATABASE_URL: "sqlite:///data/orgchart.db"
  DATABASE_ENABLE_FOREIGN_KEYS: "true"
  DATABASE_BACKUP_ENABLED: "true"
  DATABASE_BACKUP_SCHEDULE: "daily"
  DATABASE_BACKUP_DIRECTORY: "/var/backups/orgchart"
  
  # Logging configuration
  LOG_LEVEL: "WARNING"
  LOG_TO_CONSOLE: "true"
  LOG_TO_FILE: "true"
  LOG_FILE_PATH: "/var/log/orgchart/app.log"
  LOG_MAX_FILE_SIZE: "52428800"
  LOG_BACKUP_COUNT: "10"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Security configuration (non-sensitive)
  ALLOWED_HOSTS: "organigramma.yourdomain.com"
  CORS_ORIGINS: "https://organigramma.yourdomain.com"
  CSRF_PROTECTION: "true"
  SECURE_COOKIES: "true"
  HTTPS_ONLY: "true"