# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: organigramma-data-pvc
  namespace: organigramma
  labels:
    app: organigramma-web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: organigramma-logs-pvc
  namespace: organigramma
  labels:
    app: organigramma-web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: organigramma-backups-pvc
  namespace: organigramma
  labels:
    app: organigramma-web-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage