# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: organigramma-secret
  namespace: organigramma
  labels:
    app: organigramma-web-app
type: Opaque
data:
  # Base64 encoded secret key - MUST be replaced with actual secure key
  # Generate with: python -c "import secrets, base64; print(base64.b64encode(secrets.token_urlsafe(64).encode()).decode())"
  SECRET_KEY: Q0hBTkdFX1RISVNfVE9fQV9TRUNVUkVfU0VDUkVUX0tFWV9JTl9QUk9EVUNUSU9O