apiVersion: v2
name: organigramma
description: A Helm chart for Organigramma Web App - Organizational Chart Management System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - organigramma
  - organizational-chart
  - fastapi
  - python
home: https://github.com/yourusername/organigramma-web-app
sources:
  - https://github.com/yourusername/organigramma-web-app
maintainers:
  - name: Your Name
    email: your.email@example.com
dependencies: []